### ISSUE TITLE
Refused to execute script from 'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-XXXXXXXXXXXXXXXX' because its MIME type ('image/gif') is not executable.

### ISSUE THREAD

**Issue by axelraymundo** [soranoo/next-google-adsense#10]
Ads won't display and I think this is the reason.

If I open the url it's just a pixel but if I refresh it it becomes a script. Any idea how to fix this?

**Comment by soranoo** [comment]
Try:
-  Clear the cache by hard reload (`shift+F12`)
- Add gif type `<GoogleAdSense type="image/gif" ... >`

Ref:
https://stackoverflow.com/questions/69381528/refused-to-execute-script-because-its-mime-type-image-gif-is-not-executable

**Comment by axelraymundo** [comment]
Hello, I tried this, the error is gone but the ads are still not working. I see the adsbyegoogle object contains an array of empty objects though.

The experimental ads appear on mobile though

**Comment by axelraymundo** [comment]
> Try the latest beta `1.0.12b0`
> 
> Installation: `npm i next-google-adsense@1.0.12b0`

I tried the latest beta, I would say it's progress because it's a different error this time, at least it's not mimetype or errorless

`Access to script at 'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1110085181797649' from origin 'https://www.fort7.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by soranoo** [comment]
I guess that is not the package issue, try to allow `https://www.fort7.net` from your site CORS settings

**Comment by axelraymundo** [comment]
> I guess that is not the package issue, try to allow `https://www.fort7.net` from your site CORS settings

It just doesn't work on the desktop browsers, but everything works on mobile now. 

Before, the ads didn't appear on mobile too but your latest beta worked.
