### ISSUE TITLE
Show ads only at the bottom of the screen

### ISSUE THREAD

**Issue by axelraymundo** [soranoo/next-google-adsense#8]
Hello, is there a way to add this code `data-overlays="bottom"` into the `<GoogleAdSense>` tag?

**Comment by soranoo** [comment]
Yes, plz upgrade to the latest `1.0.11` version and you should able to do the following
```html
<GoogleAdSense data-overlays="bottom"/>
```

**Comment by axelraymundo** [comment]
Thank you very much! Your package is the only thing running for me at the moment.
