### ISSUE TITLE
Ad is not showing on page/route change

### ISSUE THREAD

**Issue by masonyekta** [soranoo/next-google-adsense#9]
I am showing ads in different pages, for example on the homepage, about us page and etc. When navigating to other pages (which I am using the next.js `<Link>` component) the ad does not load. If going back to the homepage again, the ad unit does not load as well unless doing a browser hard refresh.  

I am using next.js version 13.x and latest version of the package `1.0.11`

**Comment by soranoo** [comment]
Sorry for the late reply. Would you mind checking out the latest beta `1.0.12b0`?

Installation: `npm i next-google-adsense@1.0.12b0 `

Hope it works
